name: crewspace CI

env:
  S3_BUCKET_NAME: crewspace-server
  PROJECT_NAME: crewspace
  
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
      
    - name: Make zip file
      run: zip -r ./$GITHUB_SHA.zip .
      shell: bash
      
    - name: Configure AWS credential
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Upload S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3:://crewspace-server/crewspace/$GITHUB_SHA.zip
